from setuptools import setup, find_packages

setup(
    name="phorcys",
    version="0.1.0",
    author="Mesut Aktaş",
    description="A Turkish NLP Project",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mesutaktss/Phorcys",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Affero General Public License v3",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Natural Language :: Turkish",
    ],
    python_requires='>=3.6',
    install_requires=[
        "anyio",
        "certifi",
        "charset-normalizer",
        "click",
        "contourpy",
        "cycler",
        "filelock",
        "fonttools",
        "fsspec",
        "gTTS",
        "h11",
        "httpcore",
        "httpx",
        "huggingface-hub",
        "idna",
        "Jinja2",
        "joblib",
        "kiwisolver",
        "MarkupSafe",
        "matplotlib",
        "mpmath",
        "networkx",
        "nltk",
        "numpy",
        "nvidia-cublas-cu12",
        "nvidia-cuda-cupti-cu12",
        "nvidia-cuda-nvrtc-cu12",
        "nvidia-cuda-runtime-cu12",
        "nvidia-cudnn-cu12",
        "nvidia-cufft-cu12",
        "nvidia-curand-cu12",
        "nvidia-cusolver-cu12",
        "nvidia-cusparse-cu12",
        "nvidia-nccl-cu12",
        "nvidia-nvjitlink-cu12",
        "nvidia-nvtx-cu12",
        "ollama",
        "opencv-python",
        "packaging",
        "pandas",
        "pillow",
        "pydub",
        "PyMuPDF",
        "PyMuPDFb",
        "pyparsing",
        "pytesseract",
        "python-dateutil",
        "pytz",
        "PyYAML",
        "regex",
        "requests",
        "sacremoses",
        "safetensors",
        "scikit-learn",
        "scipy",
        "sentence-splitter",
        "setuptools",
        "six",
        "sniffio",
        "sympy",
        "threadpoolctl",
        "tokenizers",
        "torch",
        "tqdm",
        "transformers",
        "triton",
        "Turkish-Deasciifier",
        "typing_extensions",
        "tzdata",
        "urllib3",
        "whisper"
    ],
    include_package_data=True,
    package_data={
        'phorcys': [
            'data/badWords.txt',
            'data/stopWords.txt',
            'data/idioms.txt',
            'data/dummytext.txt',
        ],
    }
)
